//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyManagementDataLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompanyManagementResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanyManagementResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompanyManagementDataLayer.CompanyManagementResource", typeof(CompanyManagementResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All columns have values.
        /// </summary>
        internal static string AllColumnsPresent {
            get {
                return ResourceManager.GetString("AllColumnsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No client assigned for the Project.
        /// </summary>
        internal static string ClientIDForProjectMissing {
            get {
                return ResourceManager.GetString("ClientIDForProjectMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID is missing.
        /// </summary>
        internal static string ClientIDMissing {
            get {
                return ResourceManager.GetString("ClientIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client does not exist in the system.
        /// </summary>
        internal static string ClientMissing {
            get {
                return ResourceManager.GetString("ClientMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name is missing.
        /// </summary>
        internal static string ClientNameMissing {
            get {
                return ResourceManager.GetString("ClientNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Head ID is missing.
        /// </summary>
        internal static string DepartmentHeadID {
            get {
                return ResourceManager.GetString("DepartmentHeadID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No department is assigned to the Client.
        /// </summary>
        internal static string DepartmentIDForClientMissing {
            get {
                return ResourceManager.GetString("DepartmentIDForClientMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No department assigned for handling the Project.
        /// </summary>
        internal static string DepartmentIDForProjectMissing {
            get {
                return ResourceManager.GetString("DepartmentIDForProjectMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department ID is missing.
        /// </summary>
        internal static string DepartmentIDMissing {
            get {
                return ResourceManager.GetString("DepartmentIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Location is missing.
        /// </summary>
        internal static string DepartmentLocationMissing {
            get {
                return ResourceManager.GetString("DepartmentLocationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department does not exist in the system.
        /// </summary>
        internal static string DepartmentMissing {
            get {
                return ResourceManager.GetString("DepartmentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name is missing.
        /// </summary>
        internal static string DepartmentNameMissing {
            get {
                return ResourceManager.GetString("DepartmentNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Address cannot be empty.
        /// </summary>
        internal static string EmployeeAddressMissing {
            get {
                return ResourceManager.GetString("EmployeeAddressMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee with this EmployeeID already exists in the system.
        /// </summary>
        internal static string EmployeeAlreadyExists {
            get {
                return ResourceManager.GetString("EmployeeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This specific employee is already assigned this specific project.
        /// </summary>
        internal static string EmployeeAssignedToProject {
            get {
                return ResourceManager.GetString("EmployeeAssignedToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Designation cannot be empty.
        /// </summary>
        internal static string EmployeeDesignationMissing {
            get {
                return ResourceManager.GetString("EmployeeDesignationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID cannot be null or 0 or -ve.
        /// </summary>
        internal static string EmployeeIDMissing {
            get {
                return ResourceManager.GetString("EmployeeIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee does not exist. Please input an existing exployee&apos;s Employee ID.
        /// </summary>
        internal static string EmployeeMissing {
            get {
                return ResourceManager.GetString("EmployeeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name field is empty.
        /// </summary>
        internal static string EmployeeNameMissing {
            get {
                return ResourceManager.GetString("EmployeeNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee must have a role in the project.
        /// </summary>
        internal static string EmployeeRoleIDMIssing {
            get {
                return ResourceManager.GetString("EmployeeRoleIDMIssing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project with this ProjectID already exists in the system.
        /// </summary>
        internal static string ProjectAlreadyExists {
            get {
                return ResourceManager.GetString("ProjectAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ID is missing.
        /// </summary>
        internal static string ProjectIDMissing {
            get {
                return ResourceManager.GetString("ProjectIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ID has to be greater than 0.
        /// </summary>
        internal static string ProjectIDNegativeOrZero {
            get {
                return ResourceManager.GetString("ProjectIDNegativeOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project does not exist. Please input an existing project&apos;s Project ID.
        /// </summary>
        internal static string ProjectMissing {
            get {
                return ResourceManager.GetString("ProjectMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name is missing.
        /// </summary>
        internal static string ProjectNameMissing {
            get {
                return ResourceManager.GetString("ProjectNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status cannot be empty.
        /// </summary>
        internal static string StatusMissing {
            get {
                return ResourceManager.GetString("StatusMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task with this TaskID already exists.
        /// </summary>
        internal static string TaskAlreadyExists {
            get {
                return ResourceManager.GetString("TaskAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task ID is missing.
        /// </summary>
        internal static string TaskIDMissing {
            get {
                return ResourceManager.GetString("TaskIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task does not exist. Please input an existing task&apos;s Task ID.
        /// </summary>
        internal static string TaskMissing {
            get {
                return ResourceManager.GetString("TaskMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name is missing.
        /// </summary>
        internal static string TaskNameMissing {
            get {
                return ResourceManager.GetString("TaskNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology with this TechnologyID already exists in the system.
        /// </summary>
        internal static string TechnologyAlreadyExists {
            get {
                return ResourceManager.GetString("TechnologyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This specific Technology is already assigned to the specific Task.
        /// </summary>
        internal static string TechnologyAssignedToTask {
            get {
                return ResourceManager.GetString("TechnologyAssignedToTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology ID is missing.
        /// </summary>
        internal static string TechnologyIDMissing {
            get {
                return ResourceManager.GetString("TechnologyIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology does not exist. Please input an existing technology&apos;s Technology ID.
        /// </summary>
        internal static string TechnologyMissing {
            get {
                return ResourceManager.GetString("TechnologyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Name is missing.
        /// </summary>
        internal static string TechnologyNameMissing {
            get {
                return ResourceManager.GetString("TechnologyNameMissing", resourceCulture);
            }
        }
    }
}
