<?xml version="1.0" encoding="utf-8"?><Database Name="Company_2" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Company_2;Integrated Security=True" SettingsObjectName="CompanyManagementDataLayer.Properties.Settings" SettingsPropertyName="Company_2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClientName" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ClientLocation" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Client_Project" Member="Projects" ThisKey="ClientID" OtherKey="ClientID" Type="Project" />
      <Association Name="Department_Client" Member="Department" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DepartmentLocation" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DepartmentHeadID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Department_Client" Member="Clients" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Client" />
      <Association Name="Department_Employee" Member="Employees" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Employee" />
      <Association Name="Department_Project" Member="Projects" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Project" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmployeeName" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeDesignation" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="EmployeeAddress" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="EmployeeContact" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Employee_EmployeeProject" Member="EmployeeProjects" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="EmployeeProject" />
      <Association Name="Employee_EmployeeTask" Member="EmployeeTasks" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="EmployeeTask" />
      <Association Name="Department_Employee" Member="Department" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeProject" Member="EmployeeProjects">
    <Type Name="EmployeeProject">
      <Column Name="EmployeeProjectID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeRoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Employee_EmployeeProject" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
      <Association Name="Project_EmployeeProject" Member="Project" ThisKey="ProjectID" OtherKey="ProjectID" Type="Project" IsForeignKey="true" />
      <Association Name="RoleMaster_EmployeeProject" Member="RoleMaster" ThisKey="EmployeeRoleID" OtherKey="RoleID" Type="RoleMaster" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeTask" Member="EmployeeTasks">
    <Type Name="EmployeeTask">
      <Column Name="EmployeeTaskID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TaskID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeTaskStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_EmployeeTask" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
      <Association Name="StatusMaster_EmployeeTask" Member="StatusMaster" ThisKey="EmployeeTaskStatus" OtherKey="StatusID" Type="StatusMaster" IsForeignKey="true" />
      <Association Name="Task_EmployeeTask" Member="Task" ThisKey="TaskID" OtherKey="TaskID" Type="Task" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Project" Member="Projects">
    <Type Name="Project">
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProjectName" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ProjectStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Project_EmployeeProject" Member="EmployeeProjects" ThisKey="ProjectID" OtherKey="ProjectID" Type="EmployeeProject" />
      <Association Name="Project_ProjectTask" Member="ProjectTasks" ThisKey="ProjectID" OtherKey="ProjectID" Type="ProjectTask" />
      <Association Name="Project_ProjectTechnology" Member="ProjectTechnologies" ThisKey="ProjectID" OtherKey="ProjectID" Type="ProjectTechnology" />
      <Association Name="Client_Project" Member="Client" ThisKey="ClientID" OtherKey="ClientID" Type="Client" IsForeignKey="true" />
      <Association Name="Department_Project" Member="Department" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Department" IsForeignKey="true" />
      <Association Name="StatusMaster_Project" Member="StatusMaster" ThisKey="ProjectStatus" OtherKey="StatusID" Type="StatusMaster" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProjectTask" Member="ProjectTasks">
    <Type Name="ProjectTask">
      <Column Name="ProjectTaskID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TaskID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectTaskStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Project_ProjectTask" Member="Project" ThisKey="ProjectID" OtherKey="ProjectID" Type="Project" IsForeignKey="true" />
      <Association Name="StatusMaster_ProjectTask" Member="StatusMaster" ThisKey="ProjectTaskStatus" OtherKey="StatusID" Type="StatusMaster" IsForeignKey="true" />
      <Association Name="Task_ProjectTask" Member="Task" ThisKey="TaskID" OtherKey="TaskID" Type="Task" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProjectTechnology" Member="ProjectTechnologies">
    <Type Name="ProjectTechnology">
      <Column Name="ProjectTechnologyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TechnologyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectTechnologyVersionNumber" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Project_ProjectTechnology" Member="Project" ThisKey="ProjectID" OtherKey="ProjectID" Type="Project" IsForeignKey="true" />
      <Association Name="Technology_ProjectTechnology" Member="Technology" ThisKey="TechnologyID" OtherKey="TechnologyID" Type="Technology" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RoleMaster" Member="RoleMasters">
    <Type Name="RoleMaster">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="RoleDescription" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="RoleMaster_EmployeeProject" Member="EmployeeProjects" ThisKey="RoleID" OtherKey="EmployeeRoleID" Type="EmployeeProject" />
    </Type>
  </Table>
  <Table Name="dbo.StatusMaster" Member="StatusMasters">
    <Type Name="StatusMaster">
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StatusName" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="StatusDescription" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="StatusMaster_EmployeeTask" Member="EmployeeTasks" ThisKey="StatusID" OtherKey="EmployeeTaskStatus" Type="EmployeeTask" />
      <Association Name="StatusMaster_Project" Member="Projects" ThisKey="StatusID" OtherKey="ProjectStatus" Type="Project" />
      <Association Name="StatusMaster_ProjectTask" Member="ProjectTasks" ThisKey="StatusID" OtherKey="ProjectTaskStatus" Type="ProjectTask" />
    </Type>
  </Table>
  <Table Name="dbo.Task" Member="Tasks">
    <Type Name="Task">
      <Column Name="TaskID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TaskName" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TaskDescription" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Task_EmployeeTask" Member="EmployeeTasks" ThisKey="TaskID" OtherKey="TaskID" Type="EmployeeTask" />
      <Association Name="Task_ProjectTask" Member="ProjectTasks" ThisKey="TaskID" OtherKey="TaskID" Type="ProjectTask" />
      <Association Name="Task_TaskTechnology" Member="TaskTechnologies" ThisKey="TaskID" OtherKey="TaskID" Type="TaskTechnology" />
    </Type>
  </Table>
  <Table Name="dbo.TaskTechnology" Member="TaskTechnologies">
    <Type Name="TaskTechnology">
      <Column Name="TaskTechnologyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TaskID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TechnologyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Task_TaskTechnology" Member="Task" ThisKey="TaskID" OtherKey="TaskID" Type="Task" IsForeignKey="true" />
      <Association Name="Technology_TaskTechnology" Member="Technology" ThisKey="TechnologyID" OtherKey="TechnologyID" Type="Technology" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Technology" Member="Technologies">
    <Type Name="Technology">
      <Column Name="TechnologyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TechnologyName" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Technology_ProjectTechnology" Member="ProjectTechnologies" ThisKey="TechnologyID" OtherKey="TechnologyID" Type="ProjectTechnology" />
      <Association Name="Technology_TaskTechnology" Member="TaskTechnologies" ThisKey="TechnologyID" OtherKey="TechnologyID" Type="TaskTechnology" />
    </Type>
  </Table>
</Database>